// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jgZM2nZ4qC7y1cWQUTlv_7mV6jocRmU',
    appId: '1:590880612183:web:8b9631da10e492f907e812',
    messagingSenderId: '590880612183',
    projectId: 'pizzabloc-e87ca',
    authDomain: 'pizzabloc-e87ca.firebaseapp.com',
    storageBucket: 'pizzabloc-e87ca.appspot.com',
    measurementId: 'G-J092N419KH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDToeJoAiZoLm0y51jCJCs7j4siZsGgSdI',
    appId: '1:590880612183:ios:9a771eaae8a2b48707e812',
    messagingSenderId: '590880612183',
    projectId: 'pizzabloc-e87ca',
    storageBucket: 'pizzabloc-e87ca.appspot.com',
    iosBundleId: 'tech.steppay.pizzabloc',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDToeJoAiZoLm0y51jCJCs7j4siZsGgSdI',
    appId: '1:590880612183:ios:9a771eaae8a2b48707e812',
    messagingSenderId: '590880612183',
    projectId: 'pizzabloc-e87ca',
    storageBucket: 'pizzabloc-e87ca.appspot.com',
    iosBundleId: 'tech.steppay.pizzabloc',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9RzDekD3UX_VjrmQS9EgGJL_0FIy-TI',
    appId: '1:590880612183:android:2ee0adbd41fdca7707e812',
    messagingSenderId: '590880612183',
    projectId: 'pizzabloc-e87ca',
    storageBucket: 'pizzabloc-e87ca.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6jgZM2nZ4qC7y1cWQUTlv_7mV6jocRmU',
    appId: '1:590880612183:web:aa7d3ae9d7949dd807e812',
    messagingSenderId: '590880612183',
    projectId: 'pizzabloc-e87ca',
    authDomain: 'pizzabloc-e87ca.firebaseapp.com',
    storageBucket: 'pizzabloc-e87ca.appspot.com',
    measurementId: 'G-DHSLQJZ2SV',
  );

}